import * as core from '@actions/core'
import { ReplayResults } from '../config/types'

export async function generateJobSummary(results: ReplayResults): Promise<void> {
  core.info('Generating GitHub job summary')

  const { total, successful, failed, determinismViolations } = results
  const successRate = total > 0 ? ((successful / total) * 100).toFixed(1) : '0'

  await core.summary.addHeading('Temporal Replay Test Results', 2).addTable([
    [
      { data: 'Metric', header: true },
      { data: 'Count', header: true }
    ],
    ['Total Workflows', total.toString()],
    ['✅ Successful', successful.toString()],
    ['❌ Failed', failed.toString()],
    ['⚠️ Determinism Violations', determinismViolations.toString()],
    ['Success Rate', `${successRate}%`]
  ])

  // Add detailed results if there are any failures
  if (failed > 0) {
    const failedResults = results.results.filter((r) => !r.success)

    await core.summary.addHeading('Failed Replays', 3).addTable([
      [
        { data: 'Workflow ID', header: true },
        { data: 'Error Type', header: true },
        { data: 'Message', header: true }
      ],
      ...failedResults.map((result) => [
        result.workflowId,
        result.error?.type || 'Unknown',
        truncateMessage(result.error?.message || 'No error message', 100)
      ])
    ])
  } else {
    await core.summary.addRaw('\n\n✅ All replay tests passed successfully!\n\n')
  }

  await core.summary
    .addRaw('\n\n---\n\n')
    .addRaw(
      '*Generated by [Temporal Replay Testing Action](https://github.com/jamesgibbons/temporal-replay-action-ts)*'
    )
    .write()

  core.info('Job summary created')
}

function truncateMessage(message: string, maxLength: number): string {
  if (message.length <= maxLength) {
    return message
  }
  return message.substring(0, maxLength) + '...'
}
